### ISSUE TITLE
Word list should be internal data?

### ISSUE THREAD

**Issue by hadley** [gaborcsardi/praise#2]
i.e. in `R/sysdata.rda` since it's to be used by the package, not by users of the pacakge

**Comment by gaborcsardi** [comment]
I would keep it in a "text" file, actually, because then people can see it on GitHub, and also easily submit pull requests.

I know I could still build a `sysdata.rda`, but that also complicates pull requests.

I don't see this package having a lot of words, at most a couple of thousands, so I think for now the text files are fine.

**Comment by hadley** [comment]
Ok, but be prepared for awkwards when trying to access that data within `R/`

**Comment by gaborcsardi** [comment]
Maybe I'll just put it in `R/` then, as regular R objects. No trouble then I think.
